spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stock-market
    username: postgres
    password: 6040
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: abbosakramov121@gmail.com
    password: xhfq vehy myzo pmrv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    tags-sorter: alpha


